routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/contact', 'ContactController@show');
Route::post('/contact/message/send', 'ContactController@send');
//Route::get('/test', 'ContactController@test');

Route::get('/about', 'AboutController@show');
Route::get('/categories', 'CategoryController@show');
Route::get('/providers', 'ProviderController@show');
Route::get('/ultimos-trabajos', 'LastJobController@show');
Route::get('/search-service', 'SearchServiceController@show');
Route::get('/service-provider', 'ServiceProviderController@show');
Route::get('/terms-conditions', 'TermsConditionController@show');
Route::get('/privacy-policy', 'PrivacyPolicyController@show');
//public profile
Route::get('/perfil-publico/{id}', 'PublicProfileController@index');

Route::group(['middleware' => ['auth','admin'], 'namespace' => 'Admin'], function () {
    //categories
    Route::get('admin/categories', 'CategoryController@show');
    Route::post('admin/categories/add', 'CategoryController@add');
    Route::get('admin/categories/{id}/show', 'CategoryController@showCategory');
    Route::post('admin/categories/{id}/update', 'CategoryController@update');
    Route::get('admin/categories/{id}/delete', 'CategoryController@delete');
    //subcategories
    Route::get('admin/categories/{id}/subcategories', 'SubcategoryController@show');
    Route::post('admin/categories/{cat_id}/subcategories/add', 'SubcategoryController@add');
    Route::get('admin/categories/subcategories/{id}/show', 'SubcategoryController@showCategory');
    Route::post('admin/categories/subcategories/{id}/update', 'SubcategoryController@update');
    Route::get('admin/categories/subcategories/{id}/delete', 'SubcategoryController@delete');
    //images
    Route::get('admin/images', 'ImageController@index');
    Route::post('admin/images/add', 'ImageController@add');
    Route::get('admin/images/{id}/delete', 'ImageController@delete');
    //send message
    Route::get('admin/send-message', 'InternalMessageController@show');
    Route::post('admin/send-message', 'InternalMessageController@send');
    //packages
    Route::get('admin/packages', 'PackageController@show');
    Route::post('admin/packages', 'PackageController@add');

});

Route::group(['middleware' => ['auth','provider'], 'namespace' => 'Provider'], function () {

    //documents
    Route::post('doc-identity/update', 'DocumentController@updateDni');
    Route::get('doc-identity/{id}/delete', 'DocumentController@deleteDni');
    Route::post('public-service/update', 'DocumentController@updatePs');
    Route::get('public-service/{id}/delete', 'DocumentController@deletePs');


    Route::get('/verify-identity', 'VerifyIdentityController@show');

    //privacy - settings
    Route::get('/privacy-settings', 'PrivacySettingController@show');
    Route::post('/privacy-settings', 'PrivacySettingController@update');

    Route::group(['middleware' => 'doc_identity'], function () {
        //business hour
        Route::get('/business-hours', 'BusinessHourController@show');
        Route::post('/hour/add', 'BusinessHourController@add');
        Route::post('/hour/attend', 'BusinessHourController@attend');
        Route::get('/hour/{id}/delete', 'BusinessHourController@delete');
        //manage - services
        Route::get('/manage-services', 'ManageServiceController@show');
        Route::get('service/{id}/show', 'ManageServiceController@showService');
        Route::post('/services/add', 'ManageServiceController@store');
        Route::post('/services/{id}/update', 'ManageServiceController@update');
        Route::get('/services/{id}/delete', 'ManageServiceController@delete');
        //team
        Route::get('/manage-team', 'ManageTeamController@show');
//    Route::get('/manage-team/search', 'ManageTeamController@search');
        Route::get('/member/{member_id}/delete', 'ManageTeamController@delete');
        //invitation
        Route::get('/invitation', 'ManageTeamController@invitation');
        Route::get('/invitation-email', 'ManageTeamController@invitationEmail');
        //invoices
        Route::get('/invoices', 'InvoiceController@index');
        Route::get('/invoice/{id}/show', 'InvoiceController@show');
        //
        Route::get('/update-package', 'UpdatePackageController@show');
        //my-finances
        Route::get('/finances', 'FinanceController@index');

        //offer job
        Route::get('/oferta-trabajo/{id}', 'JobOfferController@show');
        Route::post('/oferta-trabajo/{id}/sentProposal', 'JobOfferController@sentProposal');
//    Route::get('/test', 'JobOfferController@test');

        //opinions
        Route::get('/opinions', 'OpinionController@index');
        Route::get('/opinions/{id}/show', 'OpinionController@show');
        Route::post('/opinions/{id}/update', 'OpinionController@update');
        //appointment
        Route::get('/appointment/{id}', 'AppointmentController@show');
        //appointment setting
        Route::get('/appointment-settings', 'AppointmentSettingController@show');
        Route::post('/schedule/add', 'AppointmentSettingController@add');
        Route::get('/schedule/{id}/delete', 'AppointmentSettingController@delete');
        //proposal sent
        Route::get('/proposal-sent', 'ProposalSentController@index');
        Route::get('/proposal-sent/{id}/show', 'ProposalSentController@show');
        //Request rating
        Route::get('request-rating', 'RatingController@index');
        Route::post('request-rating', 'RatingController@sent');
    });
});

Route::group(['middleware' => 'auth', 'namespace' => 'User'], function () {

    //insights user
    Route::get('/insights', 'InsightController@show');
    //Profile percentage
    Route::get('/profile/percentage', 'ProfilePercentageController@show');
    //Profile Settings
    Route::get('/profile-settings', 'ProfileSettingController@show');

    Route::group(['namespace' => 'ProfileSetting'], function () {
        //basic information
        Route::post('/basic-information/{user_id}/edit', 'BasicInformationController@update');
    });

    Route::group(['middleware' => 'doc_identity'], function () {
        //send message contact - claim
        Route::post('/message-contact/{to_id}/send', 'MessageController@sendContact');
        Route::post('/message-claim/{to_id}/send', 'MessageController@sendClaim');
        //chat
        Route::get('/chat', 'ChatController@show');
        Route::post('/chat/new', 'ChatController@store');
        Route::get('/chat/{id}/conversation', 'ChatController@conversation');
        Route::post('/chat/{id}/message', 'ChatController@message');

        Route::get('/gestionar-trabajos', 'JobOfferController@index');
        //post job offer
        Route::post('/publicar-oferta-trabajo', 'JobOfferController@default');
        Route::get('/publicar-oferta-trabajo/{id}', 'JobOfferController@create');
        Route::post('/publicar-oferta-trabajo/{id}', 'JobOfferController@store');
        Route::post('/publicar-oferta-trabajo/{id}/benefit/add', 'JobOfferController@addBenefit');
        Route::get('/publicar-oferta-trabajo/benefit/{id}/delete', 'JobOfferController@deleteBenefit');
        Route::post('/publicar-oferta-trabajo/{id}/image/add', 'JobOfferController@addImage');
        Route::get('/publicar-oferta-trabajo/{offer_id}/image/{id}/select', 'JobOfferController@selectImage');
        Route::get('/publicar-oferta-trabajo/image/{id}/delete', 'JobOfferController@deleteImage');
        //offer job
        Route::get('/oferta-trabajo/{id}/edit', 'JobOfferController@edit');
        Route::post('/oferta-trabajo/{id}/edit', 'JobOfferController@update');
        Route::post('/oferta-trabajo/{id}/pause', 'JobOfferController@pause');
        Route::get('/oferta-trabajo/{id}/restore', 'JobOfferController@restore');
        Route::get('/oferta-trabajo/{id}/delete', 'JobOfferController@delete');
        Route::get('/oferta-trabajo/{id}/show-pause', 'JobOfferController@showPause');
        Route::get('/oferta-trabajo/{id}/detalle', 'JobOfferController@detail');
        Route::get('/oferta-trabajo/{id}/pdf', 'JobOfferController@stream');

//    Route::get('/proposal', 'JobOfferController@proposal');

        Route::group(['namespace' => 'ProfileSetting'], function () {
            //photo profile
            Route::group(['prefix' => 'photo'], function () {
                Route::post('update', 'ProfilePhotoController@update');
                Route::get('{id}/select', 'ProfilePhotoController@select');
                Route::get('{id}/delete', 'ProfilePhotoController@delete');
            });
            //photo banner
            Route::group(['prefix' => 'banner'], function () {
                Route::post('update', 'BannerPhotoController@update');
                Route::get('{id}/select', 'BannerPhotoController@select');
                Route::get('{id}/delete', 'BannerPhotoController@delete');
            });
            //categoriees
            Route::group(['prefix' => 'categories'], function () {
                Route::post('{user_id}/add', 'CategoryController@add');
                Route::post('subcat/{user_id}/add', 'CategoryController@addSubcat');
                Route::get('{category_id}/delete', 'CategoryController@delete');
                Route::get('subcat/{category_id}/delete', 'CategoryController@deleteSubcat');
            });
            //social information
            Route::post('/social-information/{user_id}/edit', 'SocialInformationController@update');

app/Gallery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Gallery extends Model
{
    public function getImageUrlAttribute()
    {
        return '/images/galleries/'.$this->image;
    }
}

resources/views/categories.blade.php
@extends('layouts.app')

@section('styles')
    <link href="{{ asset('/select2/dist/css/select2.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('/select2/dist/css/select2-bootstrap.css') }}" rel="stylesheet" type="text/css">
@endsection

@section('banner')
    @guest
        <div class="tg-innerpagebanner">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="tg-pagetitle">
                            <h1>Categorías</h1>
                        </div>
                        <ol class="tg-breadcrumb">
                            <li><a href="/">Inicio</a></li>
                            <li class="tg-active">Categorías</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    @else
        <div class="tg-innerloginbanner">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="tg-logintitle">
                            <h1>Categorías</h1>
                        </div>
                        <div class="tg-loginsubtitle">
                            <a href="#!" onclick="window.history.back();">
                                <h1><i class="fa fa-mail-reply"></i> Volver atrás</h1>
                            </a>
                        </div>
                        <div class="tg-loginright">
                            <a href="{{ url('/insights') }}">
                                <h1>Panel de administración <i class="fa fa-mail-forward"></i></h1>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @endguest
@endsection

@section('main')
    <!--Inner Page Banner Start-->
    <div class="tg-mapinnerbanner">
        <div class="tg-searchbox">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 col-lg-push-1">
                        <form class="tg-themeform tg-formsearch">
                            <fieldset>
                                <div class="form-group">
                                    <input type="text" name="keyword" class="form-control" placeholder="Keyword">
                                </div>
                                <div class="form-group tg-inputwithicon">
                                    <div class="locate-me-wrap">
                                        <div id="location-pickr-map" class="elm-display-none"></div>
                                        <input type="text"  autocomplete="on" id="location-address" value="" name="geo_location" placeholder="Geo location" class="form-control">
                                        <a href="javascript:;" class="geolocate"><i class="fa fa-crosshairs"></i></a>
                                        <a href="javascript:;" class="geodistance"><i class="fa fa-angle-down" aria-hidden="true"></i></a>
                                        <div class="geodistance_range elm-display-none">
                                            <div class="distance-ml">Distance in&nbsp;( Miles )<span> 50</span></div>
                                            <input type="hidden" name="geo_distance" value="50" class="geo_distance" />
                                            <div class="geo_distance" id="geo_distance"></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
										<span class="tg-select">
											<select>
												<option value="Not Selected">Category</option>
												<option value="Automotive">Automotive</option>
												<option value="Beauty &amp; Personal Care">Beauty &amp; Personal Care</option>
												<option value="Business">Business</option>
												<option value="Child Care">Child Care</option>
												<option value="Cleaning">Cleaning</option>
												<option value="Computer &amp; Mobile Service">Computer &amp; Mobile Service</option>
												<option value="Food &amp; Drinks">Food &amp; Drinks</option>
												<option value="General Labor">General Labor</option>
												<option value="Construction &amp; Renovation">Construction &amp; Renovation</option>
												<option value="Health &amp; Fitness">Health &amp; Fitness</option>
												<option value="Pet Care">Pet Care</option>
												<option value="Traning &amp; Education">Traning &amp; Education</option>
												<option value="Transportation &amp; Travel">Transportation &amp; Travel</option>
											</select>
										</span>
                                </div>
                                <button class="tg-btn" type="submit"><i class="lnr lnr-magnifier"></i></button>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div id="tg-map" class="tg-map"></div>
        <div class="tg-mapcontrols">
            <span id="doc-mapplus"><i class="fa fa-plus"></i></span>
            <span id="doc-mapminus"><i class="fa fa-minus"></i></span>
            <span id="doc-lock"><i class="fa fa-lock"></i></span>
            <span id="tg-geolocation"><i class="fa fa-crosshairs"></i></span>
        </div>
        <a id="tg-btnmapview" class="tg-btn tg-btnmapview" href="#">
            <span>Map View</span>
            <i class="lnr lnr-chevron-down"></i>
        </a>
    </div>
    <!--Inner Page Banner End-->

    <!--Main Start-->
    <main id="tg-main" class="tg-main tg-haslayout" style="padding-bottom: 80px">
        <div class="container">
            <div class="row">
                <div id="tg-content" class="tg-content">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="tg-widget tg-widgetcontact" style="padding: 40px 0">
                            <div class="tg-widgettitle">
                                <h3>Buscar por:</h3>
                            </div>
                            <div class="tg-widgetcontent">
                                <form class="tg-themeform" method="GET" action="{{ url('providers') }}">
                                    <fieldset>
                                        <div class="row">
                                            <div class="col-sm-2">
                                                <div class="form-group">
                                                    <input type="text" class="form-control" name="id" placeholder="ID">
                                                </div>
                                            </div>
                                            <div class="col-sm-5">
                                                <div class="form-group">
                                                    <input type="text" class="form-control" name="username" placeholder="Nombre de usuario">
                                                </div>
                                            </div>
                                            <div class="col-sm-5">
                                                <div class="form-group">
                                                    <input type="email" class="form-control" name="email" placeholder="Email">
                                                </div>
                                            </div>
                                            <div class="col-sm-5">
                                                <div class="form-group">
                                                    <span class="tg-select" style="text-transform: none">
                                                        <input type="hidden" name="subcategory_id" class="form-control" id="select-subcategory">
                                                    </span>
                                                </div>
                                            </div>
                                            <div class="col-sm-4">
                                                <div class="form-group">
                                                    <span class="tg-select">
                                                        <select name="category_id" id="select-category">
                                                            <option value="">Categoría</option>
                                                        </select>
                                                    </span>
                                                </div>
                                            </div>
                                            <div class="col-sm-3">
                                                <button class="tg-btn tg-btn-lg" type="submit" href="javascript:void(0)">Buscar</button>
                                            </div>
                                        </div>
                                    </fieldset>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="tg-categories tg-categoriesgrid">
                        @foreach ($categories as $category)
                        <div class="col-xs-6 col-sm-6 col-md-4 col-lg-3">
                            <div class="tg-category">
                                <figure>
                                    <img src="{{ $category->image_url }}" alt="{{ $category->name }}">
                                    <figcaption class="tg-automotive">
                                        <span class="{{$category->icon->code}} tg-categoryicon"></span>
                                        <span class="tg-categoryname">{{ $category->name }}</span>
                                        <a href="{{ url(('/categories/'.$category->slug)) }}" class="tg-themetag tg-tagjobcount">
                                            <i class="fa fa-clone"></i>
                                            <em>322</em>
                                        </a>
                                    </figcaption>
                                </figure>
                            </div>
                        </div>
                        @endforeach
                    </div>
                    @include('pagination.default', ['paginator' => $categories])
                </div>
            </div>
            <hr style="border: 1px solid #5dc560; margin: 30px 0">
            <div class="row">
                <div class="col-sm-4 text-center">
                    <img src="{{ asset('images/hombre-con-letrero.png') }}" alt="Propuesta de categorias">
                </div>
                <div class="col-sm-8">
                    <label>Si tu trabajo pertenece a una categoría que aún no la tenemos registrada. ¡tranquilo! aquí tienes un espacio
                    para solicitarlo y pronto lo tendrás disponible.</label>

                    <label for="new_category">Qué categoría propones:</label>
                    <input id="new_category" name="new_category" type="text">
                    <div id="formNewCategory">
                        {{ csrf_field() }}
                        <label for="description" style="margin-top: 10px">Explícanos el área de trabajo:</label>
                        <div class="form-group">
                            <textarea class="form-control" id="description" name="description" rows="2"></textarea>
                        </div>
                        <div class="form-group">
                            <button data-send="" class="tg-btn pull-right">Enviar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <!--Main End-->
@endsection

@section('scripts')
    <script>
        $('#formNewCategory').on('change keyup keydown paste cut', 'textarea', function () {
            $(this).height(0).height(this.scrollHeight);
        }).find('textarea').change();
    </script>
    <script src="{{ asset('/select2/dist/js/select2.min.js') }}" type="text/javascript"></script>
    <script>
        $('#select-subcategory').select2({
            placeholder: 'Busca aquí: pintor, niñera, limpieza de casa…',
            ajax: {
                url: '/api/subcategories',
                dataType: 'json',
                delay: 250,

                data: function (query) {
                    return {
                        queryText: query
                    };
                },

                results: function (data) {
                    return {
                        results: data
                    };
                },

                cache: true
            }
        });
    </script>
    <script>
        $(function() {
            $('#select-subcategory').on('change', onSelectCategory);
        });

        function onSelectCategory() {
            var subcategory_id = $(this).val();
            // AJAX
            $.get('/api/subcategories/'+subcategory_id+'/category', function (data) {
                var html_select = '<option value="'+data.id+'" selected>'+data.name+'</option>';
                $('#select-category').html(html_select);
            });
        }
    </script>
    <script>
        jQuery(document).ready(function(e) {
            sp_init_map_script('tg-map');
        });
    </script>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('main')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection