routes/web.php
Route::group(['middleware' => ['auth','provider'], 'namespace' => 'Provider'], function () {

    //documents
    Route::post('doc-identity/update', 'DocumentController@updateDni');
    Route::get('doc-identity/{id}/delete', 'DocumentController@deleteDni');
    Route::post('public-service/update', 'DocumentController@updatePs');
    Route::get('public-service/{id}/delete', 'DocumentController@deletePs');


    Route::get('/verify-identity', 'VerifyIdentityController@show');

    //privacy - settings
    Route::get('/privacy-settings', 'PrivacySettingController@show');
    Route::post('/privacy-settings', 'PrivacySettingController@update');

    Route::group(['middleware' => 'doc_identity'], function () {
        //business hour
        Route::get('/business-hours', 'BusinessHourController@show');
        Route::post('/hour/add', 'BusinessHourController@add');
        Route::post('/hour/attend', 'BusinessHourController@attend');
        Route::get('/hour/{id}/delete', 'BusinessHourController@delete');
        //manage - services
        Route::get('/manage-services', 'ManageServiceController@show');
        Route::get('service/{id}/show', 'ManageServiceController@showService');
        Route::post('/services/add', 'ManageServiceController@store');
        Route::post('/services/{id}/update', 'ManageServiceController@update');
        Route::get('/services/{id}/delete', 'ManageServiceController@delete');
        //team
        Route::get('/manage-team', 'ManageTeamController@show');
//    Route::get('/manage-team/search', 'ManageTeamController@search');
        Route::get('/member/{member_id}/delete', 'ManageTeamController@delete');
        //invitation
        Route::get('/invitation', 'ManageTeamController@invitation');
        Route::get('/invitation-email', 'ManageTeamController@invitationEmail');
        //invoices
        Route::get('/invoices', 'InvoiceController@index');
        Route::get('/invoice/{id}/show', 'InvoiceController@show');
        //
        Route::get('/update-package', 'UpdatePackageController@show');
        //my-finances
        Route::get('/finances', 'FinanceController@index');

        //offer job
        Route::get('/oferta-trabajo/{id}', 'JobOfferController@show');
        Route::post('/oferta-trabajo/{id}/sentProposal', 'JobOfferController@sentProposal');
//    Route::get('/test', 'JobOfferController@test');

        //opinions
        Route::get('/opinions', 'OpinionController@index');
        Route::get('/opinions/{id}/show', 'OpinionController@show');
        Route::post('/opinions/{id}/update', 'OpinionController@update');
        //appointment
        Route::get('/appointment/{id}', 'AppointmentController@show');
        //appointment setting
        Route::get('/appointment-settings', 'AppointmentSettingController@show');
        Route::post('/schedule/add', 'AppointmentSettingController@add');
        Route::get('/schedule/{id}/delete', 'AppointmentSettingController@delete');
        //proposal sent
        Route::get('/proposal-sent', 'ProposalSentController@index');
        Route::get('/proposal-sent/{id}/show', 'ProposalSentController@show');
        //Request rating
        Route::get('request-rating', 'RatingController@index');
        Route::post('request-rating', 'RatingController@sent');
    });
});

Route::group(['middleware' => 'auth', 'namespace' => 'User'], function () {

    //insights user
    Route::get('/insights', 'InsightController@show');
    //Profile percentage
    Route::get('/profile/percentage', 'ProfilePercentageController@show');
    //Profile Settings
    Route::get('/profile-settings', 'ProfileSettingController@show');

    Route::group(['namespace' => 'ProfileSetting'], function () {
        //basic information
        Route::post('/basic-information/{user_id}/edit', 'BasicInformationController@update');
    });

    Route::group(['middleware' => 'doc_identity'], function () {
        //send message contact - claim
        Route::post('/message-contact/{to_id}/send', 'MessageController@sendContact');
        Route::post('/message-claim/{to_id}/send', 'MessageController@sendClaim');
        //chat
        Route::get('/chat', 'ChatController@show');
        Route::post('/chat/new', 'ChatController@store');
        Route::get('/chat/{id}/conversation', 'ChatController@conversation');
        Route::post('/chat/{id}/message', 'ChatController@message');

        Route::get('/gestionar-trabajos', 'JobOfferController@index');
        //post job offer
        Route::post('/publicar-oferta-trabajo', 'JobOfferController@default');
        Route::get('/publicar-oferta-trabajo/{id}', 'JobOfferController@create');
        Route::post('/publicar-oferta-trabajo/{id}', 'JobOfferController@store');
        Route::post('/publicar-oferta-trabajo/{id}/benefit/add', 'JobOfferController@addBenefit');
        Route::get('/publicar-oferta-trabajo/benefit/{id}/delete', 'JobOfferController@deleteBenefit');
        Route::post('/publicar-oferta-trabajo/{id}/image/add', 'JobOfferController@addImage');
        Route::get('/publicar-oferta-trabajo/{offer_id}/image/{id}/select', 'JobOfferController@selectImage');
        Route::get('/publicar-oferta-trabajo/image/{id}/delete', 'JobOfferController@deleteImage');
        //offer job
        Route::get('/oferta-trabajo/{id}/edit', 'JobOfferController@edit');
        Route::post('/oferta-trabajo/{id}/edit', 'JobOfferController@update');
        Route::post('/oferta-trabajo/{id}/pause', 'JobOfferController@pause');
        Route::get('/oferta-trabajo/{id}/restore', 'JobOfferController@restore');
        Route::get('/oferta-trabajo/{id}/delete', 'JobOfferController@delete');
        Route::get('/oferta-trabajo/{id}/show-pause', 'JobOfferController@showPause');
        Route::get('/oferta-trabajo/{id}/detalle', 'JobOfferController@detail');
        Route::get('/oferta-trabajo/{id}/pdf', 'JobOfferController@stream');

//    Route::get('/proposal', 'JobOfferController@proposal');

        Route::group(['namespace' => 'ProfileSetting'], function () {
            //photo profile
            Route::group(['prefix' => 'photo'], function () {
                Route::post('update', 'ProfilePhotoController@update');
                Route::get('{id}/select', 'ProfilePhotoController@select');
                Route::get('{id}/delete', 'ProfilePhotoController@delete');
            });
            //photo banner
            Route::group(['prefix' => 'banner'], function () {
                Route::post('update', 'BannerPhotoController@update');
                Route::get('{id}/select', 'BannerPhotoController@select');
                Route::get('{id}/delete', 'BannerPhotoController@delete');
            });
            //categoriees
            Route::group(['prefix' => 'categories'], function () {
                Route::post('{user_id}/add', 'CategoryController@add');
                Route::post('subcat/{user_id}/add', 'CategoryController@addSubcat');
                Route::get('{category_id}/delete', 'CategoryController@delete');
                Route::get('subcat/{category_id}/delete', 'CategoryController@deleteSubcat');
            });
            //social information
            Route::post('/social-information/{user_id}/edit', 'SocialInformationController@update');
            //presentation
            Route::post('/presentation/edit', 'PresentationController@update');
            //address
            Route::group(['prefix' => 'address'], function () {
                Route::post('{user_id}/add', 'AddressController@add');
                Route::get('{address_id}/delete', 'AddressController@delete');
            });
            //languages
            Route::group(['prefix' => 'languages'], function () {
                Route::post('{user_id}/add', 'LanguageController@add');
                Route::get('{language_id}/delete', 'LanguageController@delete');
            });
            //experience
            Route::group(['prefix' => 'experiences'], function () {
                Route::post('{user_id}/add', 'ExperienceController@add');
                Route::post('{experience_id}/update', 'ExperienceController@update');
                Route::get('{experience_id}/delete', 'ExperienceController@delete');
            });
            Route::get('/experience/{experience_id}/show', 'ExperienceController@show');
            //certificates
            Route::group(['prefix' => 'certificates'], function () {
                Route::post('{user_id}/add', 'CertificateController@add');
                Route::post('{certificate_id}/update', 'CertificateController@update');
                Route::get('{certificate_id}/delete', 'CertificateController@delete');
            });
            Route::get('/certificate/{certificate_id}/show', 'CertificateController@show');
            //qualifications
            Route::group(['prefix' => 'qualifications'], function () {
                Route::post('{user_id}/add', 'QualificationController@add');
                Route::post('{qualification_id}/update', 'QualificationController@update');
                Route::get('{qualification_id}/delete', 'QualificationController@delete');
            });
            Route::get('/qualification/{qualification_id}/show', 'QualificationController@show');
            //galleries
            Route::group(['prefix' => 'galleries'], function () {
                Route::post('{user_id}/add', 'GalleryController@add');
                Route::get('{category_id}/delete', 'GalleryController@delete');
            });
            //videos
            Route::group(['prefix' => 'videos'], function () {
                Route::post('{user_id}/add', 'VideoController@add');
                Route::get('{video_id}/delete', 'VideoController@delete');
            });
            //brochures
            Route::group(['prefix' => 'brochures'], function () {
                Route::post('{user_id}/add', 'BrochureController@add');

app/Service.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    public function getPriceValueAttribute()
    {
        if ($this->type_value == 'HFO')
            return 'S/ '.$this->price.'/ Fin Obra';

        if ($this->type_value == 'PH')
            return 'S/ '.$this->price.'/ Hora';

        if ($this->type_value == 'PV')
            return 'S/ '.$this->price.'/ Visita';

        return 'Gratuito';
    }

    public function getByAppointmentAttribute()
    {
        if ($this->appointment)
            return '(Requiere cita previa)';

        return '';
    }
}

app/Http/Controllers/User/AppointmentController.php
<?php

namespace App\Http\Controllers\User;

use App\Appointment;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AppointmentController extends Controller
{
    public function index()
    {
        $user = auth()->user();

        if($user->is_seeker){
            $appointments = Appointment::where('interested_id', auth()->id())->orWhere('provider_id', auth()->id())->orderBy('id', 'desc')->get();
        }else{
            $appointments = Appointment::where('option', 'Reservar cita')->where(function($query){
                    $query->where('interested_id', auth()->id())->orWhere('provider_id', auth()->id());
                })->orderBy('id', 'desc')->get();
        }
        return view('user.appointment', compact('appointments'));
    }

    public function show($id)
    {
        $appointment = Appointment::find($id);

        $appointment->interested_name = $appointment->interested->name;
        $appointment->service_title = $appointment->service->title;

        return $appointment;
    }
}

app/Http/Controllers/User/BookAppointmentController.php
<?php

namespace App\Http\Controllers\User;

use App\Appointment;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BookAppointmentController extends Controller
{
    public function store($id, Request $request)
    {
        $option = $request->option;
        if($option === 'Service')
            $optionDescription = 'Contratar un servicio';
        else
            $optionDescription = 'Reservar cita';

        $date = Carbon::createFromFormat('d/m/Y', $request->date);
        $time = $request->time;
        $service = $request->service;
        $information = $request->information;

        $appointment = new Appointment();
        $appointment->date = $date;
        $appointment->time = $time;
        $appointment->option = $optionDescription;
        $appointment->information = $information;

        $appointment->service_id = $service;
        $appointment->interested_id = auth()->id();
        $appointment->provider_id = $id;
        $appointment->save();

        return $appointment;
    }
}

app/Http/Controllers/User/ChatController.php
<?php

namespace App\Http\Controllers\User;

use App\Chat;
use App\Conversation;
use App\Events\MessageSent;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Pusher;
use function Sodium\compare;

class ChatController extends Controller
{
    public function show()
    {
        $chats = Chat::where('from_id', auth()->id())->orWhere('to_id', auth()->id())->get();

        $firstChat = Chat::where('from_id', auth()->id())->orWhere('to_id', auth()->id())->orderBy('created_at','desc')->first();

        $lastId = [];
        if($firstChat){
            $lastId = $firstChat->id;
    }

        return view('user.chat', compact('chats', 'lastId'));
    }

    public function store(Request $request)
    {
        $fromId = auth()->id();
        $toId = $request->to_id;
        if($fromId == $toId)
            return back();

        $firstChat = Chat::whereIn('from_id', [$fromId,$toId])->WhereIn('to_id', [$fromId,$toId])->first();

        if($firstChat){
            $chatId = $firstChat->id;
            return redirect('/chat')->with(compact('chatId'));
        }

        $chat = new Chat();
        $chat->from_id = $fromId;
        $chat->to_id = $toId;
        $chat->save();

        $chatId = $chat->id;

        return redirect('/chat')->with(compact('chatId'));
    }

    public function conversation($id)
    {
        $chat = Chat::find($id);

        $chat->conversations;

        foreach ($chat->conversations as $conversation)
        {
            $conversation->user_photo_selected = $conversation->user->photo_selected;
            $conversation->user_name = $conversation->user->name;
            $conversation->user_auth = $conversation->user_id == auth()->id() ? 1 : 0;
            $conversation->date = $conversation->getDateAttribute();
        }

        $chat->contact_name = $chat->contact->name;
        $chat->contact_phone = $chat->contact->phone ? $chat->contact->phone : '';
        $chat->contact_location = $chat->contact->location_complete;
        $chat->contact_photo_selected = $chat->contact->photo_selected;

        return $chat;
    }

    public function message(Request $request, $id)
    {
        $message = new Conversation();
        $message->message = $request->message;
        $message->user_id = auth()->id();
        $message->chat_id = $id;
        $message->save();

        $message->date = $message->getDateAttribute();

//        event(new MessageSent($message));
        $options = array(
            'cluster' => 'us2',
            'useTLS' => true
        );
        $pusher = new Pusher\Pusher(
            '01bb61e5ad5bc975923f',
            '75b7da328e4a84ac7070',
            '623514',
            $options
        );

        $pusher->trigger('my-channel', 'my-event', $message);
        return $message;
    }
}

app/Http/Controllers/User/FavouriteListingController.php
<?php

namespace App\Http\Controllers\User;

use App\UserFavorite;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class FavouriteListingController extends Controller
{
    public function add($favorite_id)
    {
        $favorite = new UserFavorite();
        $favorite->user_favorite_id = $favorite_id;
        $favorite->user_id = auth()->id();
        $favorite->save();

        return $favorite;
    }
    public function show()
    {
        $user = auth()->user();

        return view('user.favourite-listing', compact('user'));
    }

    public function delete($id)
    {
        $favorite = UserFavorite::find($id);
        $favorite->delete();

        return $favorite;
    }
}

app/Http/Controllers/User/ManageJobController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ManageJobController extends Controller
{
    public function show()
    {
        return view('user.manage-job');
    }
}

app/Http/Controllers/User/OpinionController.php
<?php

namespace App\Http\Controllers\User;

use App\Opinion;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class OpinionController extends Controller
{
    public function send($providerId, $userId, Request $request)
    {
        $rules = [
            'description' => 'required',
        ];
        $messages = [
            'description.required' => 'Es necesario ingresar una descripción',

        ];

        $validator = Validator::make($request->all(), $rules, $messages);

        if ($validator->fails())
            return response()->json($validator->errors(), 422);

        $opinion = new Opinion();
        $opinion->title = $request->title;
        $opinion->description = $request->description;
        $opinion->user_id = $userId;
        $opinion->provider_id = $providerId;
        $opinion->save();

        return $opinion;
    }
}

resources/views/user/manage-service.blade.php
@extends('layouts.app')

@section('banner')
    <div class="tg-innerpagebanner">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="tg-pagetitle">
                        <h1>Administrar mis servicios</h1>
                    </div>
                    <ol class="tg-breadcrumb">
                        <li><a href="/">Inicio</a></li>
                        <li class="tg-active">Administrar mis servicios</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('main')
    <!--Main Start-->
    <main id="tg-main" class="tg-main tg-haslayout">
        <div class="container">
            <div class="row">
                <div id="tg-twocolumns" class="tg-twocolumns">
                    <!--Menu Start-->
                    @include('user.include.menu')
                    <!--Menu End-->
                    <div class="col-xs-12 col-sm-7 col-md-8 col-lg-9">
                        <div id="tg-content" class="tg-content">
                            <div class="tg-dashboard tg-dashboardmanageservices">
                                <div class="tg-dashboardhead">
                                    <div class="tg-dashboardtitle">
                                        <h2>Administrar servicios</h2>
                                    </div>
                                    <button class="tg-btnaddservices" data-toggle="modal" data-target="#serviceModal">+ Agregar nuevo servicio</button>
                                </div>
                                <div id="uploadedService" class="tg-dashboardservices">
                                    @foreach ($user->services as $service)
                                    <div id="item-service" class="tg-dashboardservice">
                                        <div class="tg-servicetitle">
                                            <h2 id="titleText{{$service->id}}"><a href="javascript:void(0);">{{ $service->title }}</a> <span>{{ $service->by_appointment }}</span></h2>
                                        </div>
                                        <div class="tg-btntimeedit">
                                            <span id="priceText{{$service->id}}">{{ $service->price_value }}</span>
                                            <button class="tg-btnedite" data-showservice="{{ url('/service/'.$service->id.'/show') }}"><i class="lnr lnr-pencil"></i></button>
                                            <button class="tg-btndel" data-delete="{{ url('/services/'.$service->id.'/delete') }}"><i class="lnr lnr-trash"></i></button>
                                        </div>
                                    </div>
                                    @endforeach
                                    <template id="templateService">
                                        <div id="item-service" class="tg-dashboardservice">
                                            <div class="tg-servicetitle">
                                                <h2 id=""><a href="javascript:void(0);"></a> <span></span></h2>
                                            </div>
                                            <div class="tg-btntimeedit">
                                                <span id=""></span>
                                                <button class="tg-btnedite" data-showservice=""><i class="lnr lnr-pencil"></i></button>
                                                <button class="tg-btndel" data-delete=""><i class="lnr lnr-trash"></i></button>
                                            </div>
                                        </div>
                                    </template>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <!--Main End-->
    <div class="modal fade tg-socialModal" id="serviceModal" tabindex="-1">
        <div class="modal-dialog tg-modaldialog" role="document">
            <div class="modal-content tg-modalcontent">
                <div class="tg-modalhead">
                    <h2>Agregar servicio</h2>
                </div>
                <div id="alert-service"></div>
                <div class="tg-modalbody">
                    <div class="tg-themeform tg-formaddservices">
                        <fieldset>
                            <div class="row">
                                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                    <div class="form-group">
                                        <input type="text" name="text" id="title" class="form-control" placeholder="Título">
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                                    <div class="form-group">
										<span class="tg-select">
											<select id="type_value">
												<option value="">Seleccione tipo valor</option>
												<option value="PH">Por hora</option>
												<option value="PV">Por visita</option>
                                                <option value="HFO">Hasta fin de obra</option>
                                                <option value="G">Gratuito</option>
											</select>
										</span>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6" id="N">
                                    <div class="form-group">
                                        <input type="number" id="price" class="form-control" placeholder="Precio del servicio (S/)">
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                    <div class="form-group">
                                        <textarea id="description" placeholder="Descripción"></textarea>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="tg-checkbox">
                                        <input type="checkbox" name="appointment" id="appointment" value="1">
                                        <label for="appointment">Este servicio requiere cita previa</label>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                </div>
                <div class="tg-modalfoot">
                    <button class="tg-btn" data-service="{{ url('/services/add') }}">Agregar</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade tg-socialModal" id="serviceEditModal" tabindex="-1">
        <div class="modal-dialog tg-modaldialog" role="document">
            <div class="modal-content tg-modalcontent">
                <div class="tg-modalhead">
                    <h2>Editar servicio</h2>
                </div>
                <div id="alert-service"></div>
                <div class="tg-modalbody">
                    <div class="tg-themeform tg-formaddservices">
                        <fieldset>
                            <div class="row">
                                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                    <div class="form-group">
                                        <input type="text" id="titleEdit" class="form-control">
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                                    <div class="form-group">
										<span class="tg-select">
											<select id="typeValueEdit">
												<option value="">Seleccione tipo valor</option>
												<option value="PH">Por hora</option>
												<option value="PV">Por visita</option>
                                                <option value="HFO">Hasta fin de obra</option>
                                                <option value="G">Gratuito</option>
											</select>
										</span>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6" id="NEdit">
                                    <div class="form-group">
                                        <input type="number" id="priceEdit" class="form-control">
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                    <div class="form-group">
                                        <textarea id="descriptionEdit"></textarea>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="tg-checkbox">
                                        <input type="checkbox" id="appointmentEdit" value="1" checked>
                                        <label for="appointmentEdit">Este servicio requiere cita previa</label>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                </div>
                <div class="tg-modalfoot">
                    <button class="tg-btn" id="btnEdit" data-edit="">Agregar</button>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{ asset('js/manage-service/service.js') }}"></script>
    <script>
        $(function() {
            $('#type_value').change(function(){
                if ($('#type_value').val() === "G") {
                    $("#N").hide();
                }else{
                    $("#N").show();
                }
            });
        });
        $(document).on('change', function () {
            if ($('#typeValueEdit').val() === "G") {
                $("#NEdit").hide();
            }else{
                $("#NEdit").show();
            }
        })
    </script>
@endsection